<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title><?php if ($this->title!='') { echo $this->title . ' - bootphp'; } ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--[if lt IE 9]>
    <script src="/themes/bootphp/js/html5shiv.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="/themes/admin/css/jquery-ui/jquery-ui-1.10.0.custom.css">
    <link rel="stylesheet" href="/themes/admin/css/bootstrap.css">
    <link rel="stylesheet" href="/themes/admin/css/bootstrap-glyphicons.css">
    <link rel="stylesheet" href="/themes/admin/css/bootstrap-fontawesome.css">
    <link rel="stylesheet" href="/themes/admin/css/datatables.css">
    <link rel="stylesheet" href="/themes/admin/css/jquery.treeview.css" >
    <link rel="stylesheet" href="/js/plugins/select2/select2.css">
    <link rel="stylesheet" href="/themes/admin/css/TableTools.css">
    <link rel="stylesheet" href="/themes/admin/css/jquery.timepicker.css">
    <link rel="stylesheet" href="/themes/admin/css/admin.css">

    <script src="/themes/admin/js/jquery.min.js"></script>
    <script src="/themes/admin/js/jquery-ui-1.10.3.custom.min.js"></script>
    <!-- begin treeview and required libraries -->
    <script src="/themes/admin/js/jquery.cookie.js"></script>
    <script src="/themes/admin/js/jquery.treeview.js"></script>

    <!-- various admin tools -->
    <script src="/js/tinymce/tinymce.min.js"></script>
    <script src="/js/jien.js"></script><!-- need to explore -->
    <script src="/js/plugins/select2/select2.js"></script>
    <script src="/themes/admin/js/admin.php"></script><!-- need to explore -->
    <!-- being bootstrap stuff -->
    <script src="/themes/admin/js/bootstrap.js"></script>
    <script src="/themes/admin/js/jquery.timepicker.min.js"></script>
    <!-- begin data tables -->
    <script src="/themes/admin/js/jquery.dataTables.js"></script>
    <script src="/themes/admin/js/datatables-bootstrap.js"></script>
    <script src="/themes/admin/js/datatables-filtering.js"></script>
    <script src="/themes/admin/js/ZeroClipboard.js"></script>
    <script src="/themes/admin/js/TableTools.js"></script>
    <!--<script src="/themes/admin/js/FixedHeader.min.js"></script>-->
    <!-- begin Chart.js and supporting libraries -->
    <script src="/themes/admin/js/Chart.js"></script>
    <script src="/themes/admin/js/effects.js"></script>
    <!--[if lte IE 8]>
        <script src="themes/admin/js/excanvas.js"></script>
    <![endif]-->
    
    <script src="/themes/admin/js/jquery.bootstrap-growl.min.js"></script>
    
    <!-- begin custom JS -->
    <script src="/themes/admin/js/main.js"></script><!-- keep at the end, consider merge with admin.php -->

</head>

<body>

<div id="wrap">
    <nav id="menu" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <a class="navbar-brand col-lg-2" href="/">BootPHP <small><small><span class="label label-warning">Beta</span></small></small></a>
            <ul class="nav navbar-nav">
                <?php /* <li<?php if(in_array('dashboard',$this->bodyclass)) { echo ' class="active"'; } ?>>
                    <a href="/"><span class="icon-dashboard"></span> Dashboard</a>
                </li> */ ?>
                <li class="dropdown <?php if (array_intersect(array('manage', 'single'),$this->bodyclass)){ echo ' active'; } ?>">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <span class="icon-list"></span>
                        Manage
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="divider"></li>
                        <li><a href="/admin/posts">Posts</a></li>
                        <li><a href="/admin/categories">Categories</a></li>
                    </ul>
                </li>
                <?php /* <li<?php if (in_array('reports',$this->bodyclass)){ echo ' class="active"'; } ?>><a href="/admin/reports"><span class="icon-file-text"></span> Reports</a></li> */ ?>
                <li<?php if (in_array('sites',$this->bodyclass)){ echo ' class="active"'; } ?>><a href="/admin/sites/site_status/changed"><span class="icon-eye-open"></span> Site Monitor</a></li>
            </ul>
            <ul class="nav navbar-nav pull-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <span class="icon-user"></span>
                        <?php echo $_SESSION['user']['username']; ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="/admin/user/id/<?php echo $_SESSION['user']['user_id']; ?>"><span class="icon-cog"></span> My Settings</a></li>
                        <li><a href="/admin/users"><span class="icon-user"></span> Users</a></li>
                        <li><a href="/admin/configure-scaffolder"><span class="icon-wrench"></span> Scaffolder</a></li>
                        <li class="divider"></li>
                        <li class="trig_logout"><a href=""><span class="icon-off"></span> Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div><!--.container-->
    </nav><!--#menu.navbar-->

    <div id="main" class="container">
        <?php if ($this->title!='') { ?>
        <div class="row">
            <div class="col-lg-12">
                <div id="title-bar" class="page-header">
                    <div class="col-lg-6">
                        <h1 class="page-title"><?php echo $this->title; ?></h1>
                    </h5>
                    </div>
                    <div id="header-btns">
                        <div class="inner">
                        </div><!--.inner-->
                    </div><!--#header-btns.col-lg-4-->
                </div><!--#title-bar-->
            </div><!--.col-lg-12-->
        </div><!--.row-->
        <?php } ?>

        <?php echo $this->layout()->content; ?>

    </div><!--#main-->

</div><!--#wrap-->

<div id="footer">
    <div class="container">
        <p class="text-muted credit"><small>&copy; 2013 bootphp. All rights reserved.</small></p>
    </div>
</div>

</body>
</html>
