<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><?php echo $this->title; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/themes/bootphp/css/bootstrap.css" rel="stylesheet">
    <link href="/themes/bootphp/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- bootphp theme -->
    <link href="/themes/bootphp/css/style.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/themes/bootphp/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/themes/bootphp/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/themes/bootphp/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/themes/bootphp/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/themes/bootphp/ico/apple-touch-icon-57-precomposed.png">-->
    <link rel="shortcut icon" href="/themes/bootphp/ico/favicon.png">
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li class="@if(Request::is('/'))active @endif"><a href="/">Home</a></li>
          <li class="@if(Request::is('about'))active @endif"><a href="/about">About</a></li>
          <li class="@if(Request::is('contact'))active @endif"><a href="/contact">Contact</a></li>
        </ul>
        <h3 class="muted">Bootphp CMS</h3>
      </div>

      <hr>

      <?php
        echo $this->layout()->content;
      ?>

      <hr>

      <div class="footer">
        <p>&copy; Company 2013</p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/themes/bootphp/js/jquery.js"></script>
    <script src="/themes/bootphp/js/bootstrap-transition.js"></script>
    <script src="/themes/bootphp/js/bootstrap-alert.js"></script>
    <script src="/themes/bootphp/js/bootstrap-modal.js"></script>
    <script src="/themes/bootphp/js/bootstrap-dropdown.js"></script>
    <script src="/themes/bootphp/js/bootstrap-scrollspy.js"></script>
    <script src="/themes/bootphp/js/bootstrap-tab.js"></script>
    <script src="/themes/bootphp/js/bootstrap-tooltip.js"></script>
    <script src="/themes/bootphp/js/bootstrap-popover.js"></script>
    <script src="/themes/bootphp/js/bootstrap-button.js"></script>
    <script src="/themes/bootphp/js/bootstrap-collapse.js"></script>
    <script src="/themes/bootphp/js/bootstrap-carousel.js"></script>
    <script src="/themes/bootphp/js/bootstrap-typeahead.js"></script>

  </body>
</html>
