<div class="row" id="content">
    <div id="sidebar" class="col col-lg-2">
        <div class="submenu">
            <a href="/admin/accounts" class="list-group-item active">Accounts
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
            <a href="/admin/corporations" class="list-group-item">Corporations
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
            <a href="/admin/mids" class="list-group-item">MIDs
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
            <a href="/admin/banks" class="list-group-item">Banks
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
            <a href="/admin/agents" class="list-group-item">Agents
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
        </div>
    </div><!--#sidebar-->

    <div class="col col-lg-10">
        <div class="filters">
            <div class="show-hide btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Show <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> ID
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Status
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Name
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Primary Contact
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Tech Contact
                            </label>
                        </div>
                    </li>
                    <li class="close-dropdown">
                        Apply
                    </li>
                </ul>
            </div><!--#show-hide-->
        </div><!--#filters-->
        <table class="table table-striped table-bordered datatable">
            <thead>
                <tr class="advanced-search">
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th class="col-ignore col-remove"></th>
                </tr>
                <tr>
                    <th>ID</th>
                    <th>Status</th>
                    <th>Name</th>
                    <th>Primary Contact</th>
                    <th>Tech Contact</th>
                    <th>Bank</th>
                    <th class="col-actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-warning">Pending</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>TestAcct</td>
                    <td>John Smith</td>
                    <td>John Smith</td>
                    <td>Bank 10</td>
                    <td><a href="/admin/accounts-tree?3" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
            </tbody>
        </table>
    </div>
</div><!--#content.row-->
<script>

var listTable = $('.datatable').dataTable({
    "aoColumnDefs": [
        { "bSearchable": false, "bSortable": false, "aTargets": ['col-actions', 'col-checkbox', 'col-upload', 'col-ignore'] },
        { "sClass": "col-actions", "aTargets": [-1] }
    ],
    "sDom": 'T<"clear">lfrtip',
    "oTableTools": {
        "sSwfPath": "/themes/admin/swf/copy_csv_xls_pdf.swf",
        "aButtons": [
            {
                "sExtends": "xls",
                "sButtonText": '<span class="icon-share-alt"></span> Export'
            }
        ]
    }
});

</script>