<div class="row" id="content">

    <div class="tree-single col-lg-10 col-lg-offset-2">
        <form class="form-horizontal">
            <div class="row">
                <h2 class="col-lg-12">TestBank, Inc. <span class="label label-default single-type">Bank</span></h2>
                <p class="col-lg-12">See all <a href="">accounts</a>, <a href="">corporations</a> and <a href="">MIDs</a> associated with this bank.</p>
            </div>
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab-basic" data-toggle="tab">Basic Information</a></li>
                <li><a href="#tab-notes" data-toggle="tab">Notes</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab-basic">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="id" class="col-lg-4 control-label">ID</label>
                                <div class="col-lg-8">
                                    <input type="text" name="id" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="name" class="col-lg-4 control-label">Bank Name</label>
                                <div class="col-lg-8">
                                    <input type="text" name="name" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="status" class="col-lg-4 control-label">Status</label>
                                <div class="col-lg-8">
                                    <select name="status" class="form-control">
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="status" class="col-lg-4 control-label">Description</label>
                                <div class="col-lg-8">
                                    <input type="text" name="description" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="holder_name" class="col-lg-4 control-label">Holder Name</label>
                                <div class="col-lg-8">
                                    <input type="text" name="holder_name" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="swift" class="col-lg-4 control-label">SWIFT</label>
                                <div class="col-lg-8">
                                    <input type="text" name="swift" class="form-control">
                                    <p class="help-block">7-10 characters</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="iban" class="col-lg-4 control-label">IBAN</label>
                                <div class="col-lg-8">
                                    <input type="text" name="iban" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="currency" class="col-lg-4 control-label">Currency</label>
                                <div class="col-lg-8">
                                    <input type="text" name="holder_name" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="routing_no" class="col-lg-4 control-label">Routing Number</label>
                                <div class="col-lg-8">
                                    <select class="form-control" name="currency">
                                        <option value="">Add rates...</option>
                                        <option value="usd">USD</option>
                                        <option value="eur">EUR</option>
                                        <option value="gbp">GBP</option>
                                        <option value="cad">CAD</option>
                                        <option value="aud">AUD</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <h4 class="col-lg-8 col-lg-offset-4">Merchant Data Configuration</h4>
                            </div>
                            <div class="form-group">
                                <label for="variable1" class="col-lg-4 control-label">Variable 1</label>
                                <div class="col-lg-8">
                                    <input type="text" name="variable1" class="form-control">
                                </div>
                            </div>
                        </div><!--.col.col-lg-6-->
                        <div class="col-lg-6">
        
                        </div><!--.col.col-lg-6-->
                    </div><!--.row-->
                </div><!--.tab-pane-->
                <div class="tab-pane" id="tab-notes">
                    <table class="table table-striped table-bordered datatable with-check notes">
                        <thead>
                            <tr class="advanced-search">
                                <th class="col-ignore"></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th class="col-ignore col-remove">&nbsp;</th>
                            </tr>
                            <tr>
                                <th class="col-checkbox"><input type="checkbox"></th>
                                <th class="col-note">Note</th>
                                <th>Created</th>
                                <th>Modified</th>
                                <th class="col-actions">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><input type="checkbox"></td>
                                <td>
                                    <div class="cell-note" contenteditable="false">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    </div>
                                </td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-action btn-edit ttip" title="Edit"><span class="icon-pencil"></span></button>
                                    <button type="button" class="btn btn-danger btn-action btn-delete ttip" title="Delete"><span class="icon-trash"></span></button>
                                </td>
                            </tr>
                            <tr>
                                <td><input type="checkbox"></td>
                                <td>
                                    <div class="cell-note" contenteditable="false">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    </div>
                                </td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td class="col-actions">
                                    <button type="button" class="btn btn-primary btn-action btn-edit ttip" title="Edit"><span class="icon-pencil"></span></button>
                                    <button type="button" class="btn btn-danger btn-action btn-delete ttip" title="Delete"><span class="icon-trash"></span></button>
                                </td>
                            </tr>
                            <tr>
                                <td><input type="checkbox"></td>
                                <td>
                                    <div class="cell-note" contenteditable="false">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    </div>
                                </td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td class="col-actions">
                                    <button type="button" class="btn btn-primary btn-action btn-edit ttip" title="Edit"><span class="icon-pencil"></span></button>
                                    <button type="button" class="btn btn-danger btn-action btn-delete ttip" title="Delete"><span class="icon-trash"></span></button>
                                </td>
                            </tr>
                            <tr>
                                <td><input type="checkbox"></td>
                                <td>
                                    <div class="cell-note" contenteditable="false">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    </div>
                                </td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td class="col-actions">
                                    <button type="button" class="btn btn-primary btn-action btn-edit ttip" title="Edit"><span class="icon-pencil"></span></button>
                                    <button type="button" class="btn btn-danger btn-action btn-delete ttip" title="Delete"><span class="icon-trash"></span></button>
                                </td>
                            </tr>
                            <tr>
                                <td><input type="checkbox"></td>
                                <td>
                                    <div class="cell-note" contenteditable="false">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    </div>
                                </td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td class="col-actions">
                                    <button type="button" class="btn btn-primary btn-action btn-edit ttip" title="Edit"><span class="icon-pencil"></span></button>
                                    <button type="button" class="btn btn-danger btn-action btn-delete ttip" title="Delete"><span class="icon-trash"></span></button>
                                </td>
                            </tr>
                            <tr>
                                <td><input type="checkbox"></td>
                                <td>
                                    <div class="cell-note" contenteditable="false">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    </div>
                                </td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td class="col-actions">
                                    <button type="button" class="btn btn-primary btn-action btn-edit ttip" title="Edit"><span class="icon-pencil"></span></button>
                                    <button type="button" class="btn btn-danger btn-action btn-delete ttip" title="Delete"><span class="icon-trash"></span></button>
                                </td>
                            </tr>
                            <tr>
                                <td><input type="checkbox"></td>
                                <td>
                                    <div class="cell-note" contenteditable="false">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    </div>
                                </td>w
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td>2013-05-20 5:35p<br>
                                    <em>by admin</em></td>
                                <td class="col-actions">
                                    <button type="button" class="btn btn-primary btn-action btn-edit ttip" title="Edit"><span class="icon-pencil"></span></button>
                                    <button type="button" class="btn btn-danger btn-action btn-delete ttip" title="Delete"><span class="icon-trash"></span></button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="clear"></div>
                    <div class="row">
                        <div class="col-lg-12">
                            <h3 style="margin-top:1em">Add New Note</h3>
                        </div><!--.col-lg-12-->
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <textarea name="new_note" id="new-note" rows="6" class="input-note form-control" placeholder="Your note text..."></textarea><br>
                            <button type="button" class="btn btn-primary">Add Note</button>
                        </div><!--.col-lg-12-->
                    </div>
                </div><!--#notes.tab-pane-->
            </div><!--.tab-content-->
        </form>
    </div><!--.tree-single-->
</div><!--.row-->

<script>

var notesTable = $('.table.notes').dataTable({
                    "aoColumnDefs": [
                        { "bSearchable": false, "bSortable": false, "aTargets": ['col-actions', 'col-checkbox', 'col-upload', 'col-ignore'] },
                        { "sClass": "col-actions", "aTargets": [-1] },
                        { "sClass": "col-checkbox", "aTargets": [0] }
                    ]
                });
</script>