<?php
$type = $this->params('type') != '' ? $this->params('type') : ($this->data->row('type') ? $this->data->row('type') : 'Post');
?>






<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon">
					<i class="icon-align-justify"></i>
				</span>
				<h5><?php echo ucfirst($this->model); ?> form</h5>
			</div>

			<div class="widget-content nopadding">
				<form action="/admin/data" method="POST" class="trig_save form-horizontal">
				<input type="hidden" name="model" value="<?php echo $this->model; ?>">
		  		<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">

					<div class="control-group">
						<label class="control-label"><?php echo $label; ?></label>
						<div class="controls">


							<div class="control-group">
								<label class="control-label">Type</label>
								<div class="controls">
									<select class="dropdown" name="type">
										<?php
										$category_types_rows = Jien::model("Category")->select('type')->groupBy("type")->get()->rows();
										$category_types = array("");
										foreach($category_types_rows AS $row){
											$category_types[$row['type']] = $row['type'];
										}
										echo $this->dropdownOptions($category_types, $this->params('type', $this->data->row('type', 'Post')));
										?>
										<option value="Add">--- add new ---</option>
									</select>

									<div id="type_new_box" style="display: none;">
										<input id="type_new" type="text">
									</div>

								</div>
							</div>

							<div class="control-group">
								<label class="control-label">Parent</label>
								<div class="controls">
									<select name='parent_id'>
										<?php echo $this->CategoryDropdown($type, $this->data->row('parent_id') ? $this->data->row('parent_id') : $this->params('category_id')); ?>
									</select>
								</div>
							</div>

							<div class="control-group">
								<label class="control-label">Category</label>
								<div class="controls">
									<input class='large' name='category' value="<?php echo $this->data->row('category') ? $this->data->row('category') : ''; ?>" type='text'>
								</div>
							</div>


						</div>
					</div>

					<div class="form-actions">
						<input type="submit" class="btn btn-success primary" value="Save changes">&nbsp;<button type="reset" class="btn back">Cancel</button>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>

<script>


$(document).ready(function(){

	$('select[name=type]').change(function(){

		if($(this).val() == "Add"){

			$('#type_new_box').show();
			$('select[name=type]').attr('name', 'type_old');
			$('#type_new').attr('name', 'type');

		}else{

			$('#type_new_box').hide();
			$('select[name=type]').attr('name', 'type');
			$('#type_new').attr('name', 'type_old');

			$.getJSON("/api/categories", {type: $(this).val()}, function(res){
				$('select[name=parent_id]').html(res.result.html);
				console.log(res);
			});
		}
	});
});
</script>