<div id="content" class="row">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-import" data-toggle="tab">Import from table</a></li>
        <li><a href="#tab-table" data-toggle="tab">Create table</a></li>
    </ul>
    
    <div class="tab-content">
        <div class="tab-pane active" id="tab-import">
            <h3>Generate admin related files from table</h3>
            <p>Generate model, controller, and admin CRUD view files.</p>
            <div class="row">
                <div class="input-group col-lg-3">
                    <input id="scaffold_model" type="text" placeholder="e.g. 'Product'" class="form-control">
                    <div class="input-group-btn">
                        <button class="trig_scaffold_model btn btn-primary">Generate</button>
                    </div>
                </div>
            </div>
        </div><!--.tab-pane-->
        <div class="tab-pane" id="tab-table">
            <table class="table table-striped table-bordered" id="table-create-table">
                <thead>
                    <tr>
                        <th>Column Name</th>
                        <th>Type</th>
                        <th style="width:80px">Length</th>
                        <th style="width:408px">Default</th>
                        <th class="col-actions">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><input type="text" name="r1_column" class="ct-column-name form-control"></td>
                        <td>
                            <select name="r1_column" class="ct-column form-control">
                                <option value="int">int</option>
                                <option value="varchar">varchar</option>
                                <option value="text">text</option>
                                <option value="decimal">decimal</option>
                                <option value="datetime">datetime</option>
                                <option value="timestamp">timestamp</option>
                            </select>
                        </td>
                        <td><input type="text" name="r1_length" class="ct-length form-control"></td>
                        <td>
                            <select name="r1_default" class="ct-default form-control">
                                <option value="auto_increment">auto_increment</option>
                                <option value="null">NULL</option>
                                <option value="not_null" selected>NOT NULL</option>
                                <option value="custom">As defined...</option>
                            </select>
                        </td>
                        <td>
                            <a href="#" class="btn btn-danger btn-delete ttip" title="Delete"><span class="icon-trash"></span></a>
                        </td> 
                    </tr>
                </tbody>
            </table>
            <button class="btn btn-default" id="add-row"><span class="icon-plus"></span> Add row</button>
            <div class="pull-right">
                <button class="btn btn-primary"><span class="icon-ok"></span> Create table</button>
            </div>
        </div><!--.tab-pane-->
    </div><!--.tab-content-->
</div><!--#content.row-->

<script>

$('.trig_scaffold_model').click(function(e){
    e.preventDefault();
    var model = $("#scaffold_model").val();
    if(model == ""){
        alert("oops, you forgot to put in model name");
    }else{
        var c = confirm("This will overwrite any model-related files you may already have. Are you sure?");
        if(c){
            location.href = '/admin/scaffold/?model='+model;
        }
    }
});

var row_count = 1;
$('#add-row').click(function(e){
    row_count++;
    
    var html = '<tr>';
    html += '<td><input type="text" name="r' + row_count + '_column" class="ct-column-name form-control"></td>';
    html += '<td>';
    html += '<select name="r' + row_count + '_column" class="ct-column form-control">';
    html += '<option value="int">int</option>';
    html += '<option value="varchar">varchar</option>';
    html += '<option value="text">text</option>';
    html += '<option value="decimal">decimal</option>';
    html += '<option value="datetime">datetime</option>';
    html += '<option value="timestamp">timestamp</option>';
    html += '</select>';
    html += '</td>';
    html += '<td><input type="text" name="r' + row_count + '_length" class="ct-length form-control"></td>';
    html += '<td><select name="r' + row_count + '_default" class="ct-default form-control">';
    html += '<option value="auto_increment">auto_increment</option>';
    html += '<option value="null">NULL</option>';
    html += '<option value="not_null" selected>NOT NULL</option>';
    html += '<option value="custom">as defined...</option>';
    html += '</select></td>';
    html += '<td>';
    html += '<a href="#" class="btn btn-danger btn-delete ttip" title="Delete"><span class="icon-trash"></span></a>';
    html += '</td>';
    html += '</tr>';
    $('#table-create-table').append(html);
});

$('#tab-table').on('change', '.ct-default', function(e){
    if ($(this).val() == 'custom') {
        var row_count = $(this).attr('name').substring(1,2);
        var input = '<input type="text" name="r' + row_count + '_default_custom" class="ct-default-custom form-control" placeholder="Enter default value...">';
        $(this).after(input);
        $(this).parent().find('select').addClass('ct-default-condensed');
    } else {
        $(this).parent().find('select').removeClass('ct-default-condensed').parent().find('.ct-default-custom').remove();
    }
});

</script>