<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon">
					<i class="icon-align-justify"></i>
				</span>
				<h5>Contact form</h5>
			</div>

			<div class="widget-content nopadding">
				<form action="/admin/data" method="POST" class="trig_save form-horizontal">
				<input type="hidden" name="model" value="Contact">
		  		<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">

		  			<div class="control-group">
								<label class="control-label">Name</label>
								<div class="controls">
									<input class="large" name="name" value="<?php echo $this->data->row("name") ? $this->data->row("name") : ""; ?>" type="text">
								</div>
							</div>
<div class="control-group">
								<label class="control-label">Email</label>
								<div class="controls">
									<input class="large" name="email" value="<?php echo $this->data->row("email") ? $this->data->row("email") : ""; ?>" type="text">
								</div>
							</div>
<div class="control-group">
								<label class="control-label">Subject</label>
								<div class="controls">
									<input class="large" name="subject" value="<?php echo $this->data->row("subject") ? $this->data->row("subject") : ""; ?>" type="text">
								</div>
							</div>
<div class="control-group">
								<label class="control-label">Message</label>
								<div class="controls">
									<input class="large" name="message" value="<?php echo $this->data->row("message") ? $this->data->row("message") : ""; ?>" type="text">
								</div>
							</div>


					<div class="form-actions">
						<input type="submit" class="btn btn-success primary" value="Save changes">&nbsp;<button type="reset" class="btn back">Cancel</button>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>

<script>


$(document).ready(function(){

	$('select[name=type]').change(function(){

		if($(this).val() == "Add"){

			$('#type_new_box').show();
			$('select[name=type]').attr('name', 'type_old');
			$('#type_new').attr('name', 'type');

		}else{

			$('#type_new_box').hide();
			$('select[name=type]').attr('name', 'type');
			$('#type_new').attr('name', 'type_old');

			$.getJSON("/api/categories", {type: $(this).val()}, function(res){
				$('select[name=parent_id]').html(res.result.html);
				console.log(res);
			});
		}
	});
});
</script>