<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-title">

				 <h5>List Coupon</h5>
				<div class="buttons">
					<a title="Add a new coupon" class="btn btn-success btn-mini" href="/admin/coupon"><i class="icon-plus icon-white"></i> Add New</a>
				</div>
			</div>
			<div class="widget-content nopadding">
				<table class="table table-bordered table-striped with-check">
					<thead>
						<tr>
							<th class="header"><input type="checkbox" id="title-checkbox" name="title-checkbox" /></th>
							<th class="header" rel="coupon.coupon_id">#</th>
							<th class='header' rel='coupon.coupon_type'>Coupon Type</th><th class='header' rel='coupon.coupon_code'>Coupon Code</th><th class='header' rel='coupon.coupon_value'>Coupon Value</th><th class='header' rel='coupon.num_used'>Used</th><th class='header' rel='coupon.status'>Status</th>
				            <th class="header" rel="coupon.created">Created</th>
				            <th class="header">Action</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach($this->data->rows() AS $key=>$value){ ?>
						<tr>
							<td><input type="checkbox" /></td>
							<td><?php echo $value['coupon_id']; ?></td>
							<td><?php echo $value['coupon_type']; ?></td><td><?php echo $value['coupon_code']; ?></td><td><?php echo $value['coupon_value']; ?></td><td><?php echo $value['num_used']; ?></td><td><?php echo $value['status']; ?></td>
				            <td><?php echo date("m/d/y", strtotime($value['created'])); ?></td>
				            <td>
				            	<a href="/admin/coupon/id/<?php echo $value[$this->primary]; ?>" class="btn btn-primary btn-mini"><i class="icon-pencil icon-white"></i> View</a>
				            	<a href="/admin/delete/?model=Coupon&id=<?php echo $value[$this->primary];; ?>" rel="model=Coupon|id=<?php echo $value[$this->primary]; ?>" class="btn btn-danger btn-mini trig_delete"><i class="icon-remove icon-white"></i> Delete</a>
				            </td>
						</tr>
						<?php } ?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $this->pager($this->data->pager(), 'partials/pager/pager.phtml'); ?>
	</div>
</div>