<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon">
					<i class="icon-align-justify"></i>
				</span>
				<h5>Coupon form</h5>
			</div>

			<div class="widget-content nopadding">
				<form action="/admin/data" method="POST" class="trig_save form-horizontal">
				<input type="hidden" name="model" value="Coupon">
		  		<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">

		  			<div class="control-group">

		  						<label class="control-label">Coupon Code</label>
								<div class="controls">
									<input class="large" name="coupon_code" value="<?php echo $this->data->row("coupon_code") ? $this->data->row("coupon_code") : ""; ?>" type="text">
								</div>
							</div>

							<div class="control-group">
								<label class="control-label">Coupon Type</label>
								<div class="controls">
									<select name='coupon_type'>
										<?php echo $this->dropdownOptions(array(
											"percent"	=>	"% off total price",
											"trial"	=>	"# of days free",
										), $this->data->row('coupon_type'), 'percent'); ?>
									</select>
								</div>
							</div>


							<div class="control-group">
							<label class="control-label">Value</label>
								<div class="controls">
									<input class="large" name="coupon_value" value="<?php echo $this->data->row("coupon_value") ? $this->data->row("coupon_value") : ""; ?>" type="text">
								</div>
							</div>

							<div class="control-group">
							<label class="control-label">Product #</label>
								<div class="controls">
									<input class="large" name="product_id" value="<?php echo $this->data->row("product_id") ? $this->data->row("product_id") : ""; ?>" type="text" placeholder="Optional">
								</div>
							</div>

							<div class="control-group">
							<label class="control-label">Status</label>
								<div class="controls">
									<select name='status'>
										<?php echo $this->dropdownOptions(array(
											"pending"	=>	"Pending",
											"published"	=>	"Published",
										), $this->data->row('status'), 'published'); ?>
									</select>
								</div>
							</div>


					<div class="form-actions">
						<input type="submit" class="btn btn-success primary" value="Save changes">&nbsp;<button type="reset" class="btn back">Cancel</button>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>

<script>

$(document).ready(function(){

});
</script>