<div class="row" id="content">
    <div id="sidebar" class="col col-lg-2">
        <div class="list-group submenu">
            <a href="/admin/accounts" class="list-group-item">Accounts
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
            <a href="/admin/corporations" class="list-group-item">Corporations
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
            <a href="/admin/mids" class="list-group-item active">MIDs
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
            <a href="/admin/banks" class="list-group-item">Banks
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
            <a href="/admin/agents" class="list-group-item">Agents
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
        </div>
    </div><!--#sidebar-->

    <div class="col col-lg-10">
        <div class="filters">
            <div class="show-hide btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Show <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> ID
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Currency
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Status
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Qual
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Accounts
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Corporation
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Paysite
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Descriptor 1
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Descriptor 2
                            </label>
                        </div>
                    </li>
                    <li class="close-dropdown">
                        Apply
                    </li>
                </ul>
            </div><!--#show-hide-->
        </div><!--#filters-->
        <table class="table table-striped table-bordered datatable">
            <thead>
                <tr class="advanced-search">
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th class="col-ignore col-remove"></th>
                </tr>
                <tr>
                    <th>ID</th>
                    <th>Currency</th>
                    <th>Status</th>
                    <th>Qual</th>
                    <th>Account</th>
                    <th>Corporation</th>
                    <th>Paysite</th>
                    <th>Descriptor 1</th>
                    <th>Descriptor 2</th>
                    <th class="col-actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
                <tr>
                    <td>34034</td>
                    <td>USD</td>
                    <td><span class="label label-success">Active</span></td>
                    <td>693bf676</td>
                    <td><a href="#">TestAcct</a></td>
                    <td><a href="#">TestCorp</a></td>
                    <td>trustpay.com</td>
                    <td>trustpay</td>
                    <td>test</td>
                    <td><a href="/admin/mids-tree" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a></td>
                </tr>
            </tbody>
        </table>
    </div>
</div><!-- #content.row -->
<script>
var listTable = $('.datatable').dataTable({
                    "aoColumnDefs": [
                        { "bSearchable": false, "bSortable": false, "aTargets": ['col-actions', 'col-checkbox', 'col-upload', 'col-ignore'] },
                        { "sClass": "col-actions", "aTargets": [-1] }
                    ],
                    "sDom": 'T<"clear">lfrtip',
                    "oTableTools": {
                        "sSwfPath": "/themes/admin/swf/copy_csv_xls_pdf.swf",
                        "aButtons": [
                            {
                                "sExtends": "xls",
                                "sButtonText": '<span class="icon-share-alt"></span> Export'
                            }
                        ]
                    }
                });
</script>