<div id="content" class="row">
    <div id="sidebar" class="col col-lg-2">
        <div class="list-group submenu">
            <a href="" class="list-group-item active">Overview <span class="icon-large icon-chevron-right pull-right"></span></a>
            <a href="" class="list-group-item">Authorizations <span class="icon-large icon-chevron-right pull-right"></span></a>
            <a href="" class="list-group-item">Completed <span class="icon-large icon-chevron-right pull-right"></span></a>
            <a href="" class="list-group-item">Adjustments <span class="icon-large icon-chevron-right pull-right"></span></a>
            <a href="" class="list-group-item">Chargebacks <span class="icon-large icon-chevron-right pull-right"></span></a>
            <a href="" class="list-group-item">Retrievals <span class="icon-large icon-chevron-right pull-right"></span></a>
            <a href="" class="list-group-item">Banks <span class="icon-large icon-chevron-right pull-right"></span></a>
        </div>
    </div><!--#sidebar-->
    <div class="col-lg-10">
        <div id="filters">
            <a href="" class="btn btn-default expand-collapse-all"><span class="icon icon-plus-sign"></span> Expand All</a>
            <div class="date-range">
                <div class="input-group" style="width:123px;float:left;margin-right:4px">
                    <input type="text" name="start_date" class="form-control input-date" placeholder="Start Date">
                    <span class="input-group-addon"><span class="icon-calendar"></span></span>
                </div>
                <div class="input-group" style="width:123px;float:left">
                    <input type="text" name="start_time" class="form-control input-time" placeholder="Start Time">
                    <span class="input-group-addon"><span class="icon-time"></span></span>
                </div>
                <label style="float:left;padding-top:8px;margin-right:6px;margin-left:6px"> to </label>
                <div class="input-group" style="width:123px;float:left;margin-right:4px">
                    <input type="text" name="end_date" class="form-control input-date" placeholder="End Date">
                    <span class="input-group-addon"><span class="icon-calendar"></span></span>
                </div>
                <div class="input-group" style="width:123px;float:left;margin-right:4px">
                    <input type="text" name="end_time" class="form-control input-time" placeholder="End Time">
                    <span class="input-group-addon"><span class="icon-time"></span></span>
                </div>
                <button type="button" class="btn btn-default">Go</button>
            </div><!--.date-range-->
            <div class="clearfix"></div>
        </div><!--.filters-->
        <div class="clearfix"></div>
        <table class="table table-bordered table-striped datatable report">
            <thead>
                <tr>
                    <th class="col-sort"></th>
                    <th class="col-ignore">&nbsp;</th>
                    <th colspan="2" class="col-ignore">Authorization Approved</th>
                    <th colspan="2" class="col-ignore">Completed Approved</th>
                    <th colspan="2" class="col-ignore">Adjustments Approved</th>
                </tr>
                <tr>
                    <th class="col-sort"></th>
                    <th class="col-ignore">&nbsp;</th>
                    <th>Transaction Count</th>
                    <th>Amount</th>
                    <th>Transaction Count</th>
                    <th>Amount</th>
                    <th>Transaction Count</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>0</td>
                    <td></td>
                    <td>9</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>0</td>
                    <td></td>
                    <td>10</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>0</td>
                    <td></td>
                    <td>3</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1</td>
                    <td class="col-label">Totals</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1</td>
                    <td class="col-label expand-row">TestAcct</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr class="details details-1">
                    <td>2</td>
                    <td class="col-label expand-row indent">TestCorp</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr class="details details-2 details-2a">
                    <td>3</td>
                    <td class="col-label expand-row indent">EUR</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr class="details details-3 details-3a">
                    <td>4</td>
                    <td class="indent">
                        <a href="" class="label">33989</a> credoraxtest.com<br>
                        <small class="text-muted">Credorax Test / Credorax Test</small>
                    </td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr class="details details-3 details-3a">
                    <td>5</td>
                    <td class="indent">a</td>
                    <td>hjhjh</td>
                    <td>hjh</td>
                    <td>jhjh</td>
                    <td>hjhj</td>
                    <td>ah</td>
                    <td>hjhjh</td>
                </tr>
                <tr class="details details-2 details-2b">
                    <td>6</td>
                    <td class="col-label expand-row indent">USD</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr class="details details-3 details-3b">
                    <td>7</td>
                    <td class="indent">
                        <a href="" class="label">999999</a> credoraxtest.com<br>
                        <small class="text-muted">Credorax Test / Credorax Test</small>
                    </td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr class="details details-3 details-3b">
                    <td>8</td>
                    <td class="indent">a</td>
                    <td>hjhjh</td>
                    <td>hjh</td>
                    <td>jhjh</td>
                    <td>hjhj</td>
                    <td>ah</td>
                    <td>hjhjh</td>
                </tr>
            </tbody>
        </table>
    </div><!--.col-lg-10-->
</div><!--#content.row-->
<script>
$(document).ready(function(){
    /*
     * Insert a 'details' column to the table
     */
    var nCloneTh = document.createElement( 'th' );
    var nCloneTd = document.createElement( 'span' );
    nCloneTd.innerHTML = '';
    nCloneTd.className = "icon icon-plus-sign expand";
     
    $('.datatable thead tr').each( function () {
        //this.insertBefore( nCloneTh, this.childNodes[0] );
    });
     
    $('.expand-row').each( function () {
        $(this).prepend(' ');
        $(this).prepend(nCloneTd.cloneNode( true ) );
    });

    /* Add event listener for opening and closing details
     * Note that the indicator for showing which row is open is not controlled by DataTables,
     * rather it is done here
     */
    $('.expand-row').on('click', function () {
        
        var $thisrow = $(this).parent();

        $thisrow.find('.icon').toggleClass('icon-minus-sign').toggleClass('icon-plus-sign');

        if ($thisrow.hasClass('details')) {
            if ($thisrow.hasClass('details-1')) {
                $('.details-2').toggleClass('show');
                $('.details-3').removeClass('show');
                $('.details-2 .icon').removeClass('icon-minus-sign').addClass('icon-plus-sign');
            }
            if ($thisrow.hasClass('details-2a')) {
                $('.details-3a').toggleClass('show');
            }

            if ($thisrow.hasClass('details-2b')) {
                $('.details-3b').toggleClass('show');
            }

        } else {
            $('.details-1').toggleClass('show');
            if ( $thisrow.find('.icon').hasClass('icon-plus-sign') ) {
                $('.details-2, .details-3').removeClass('show');
                $('.details .icon').removeClass('icon-minus-sign').addClass('icon-plus-sign');
            }
        }
    });
     
    
    // Initialize DataTables, with no sorting on the 'details' column
    var reportsTable = $('.datatable').dataTable({
        "aaSortingFixed": [[0,'asc']],
        "aoColumnDefs": [
            { "bSearchable": false, "bSortable": false, "aTargets": ['col-actions', 'col-checkbox', 'col-upload', 'col-ignore'] }, // Disabled sorting 
            { "bSearchable": false, "bVisible": false, "aTargets": ['col-sort'] } // Allow for fixed rows using hidden column values 
        ],
        "iDisplayLength" : -1,
    });
     
});
</script>