<div class="row">
    <div id="sidebar" class="col-lg-2">
        <div class="list-group submenu">
            <a href="/admin/sites/site_status/changed" class="list-group-item<?php if(strstr($_SERVER['REQUEST_URI'], '/admin/sites/site_status/changed')){ echo ' active'; } ?>">
                <span class="icon-large icon-chevron-right pull-right"></span>
                Sites changed
            </a>
            <a href="/admin/sites/site_status/active" class="list-group-item<?php if(strstr($_SERVER['REQUEST_URI'], '/admin/sites/site_status/active')){ echo ' active'; } ?>">
                Active sites
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
            <a href="/admin/sites/site_status/_SERVER" class="list-group-item<?php if(strstr($_SERVER['REQUEST_URI'], '/admin/sites/site_status/_SERVER')){ echo ' active'; } ?>">
                Inactive sites
                <span class="icon-large icon-chevron-right pull-right"></span>
            </a>
        </div>
    </div><!--#sidebar-->
    <div class="col-lg-10">
        <div class="filters">
            <div class="show-hide btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Show <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Checkbox
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Screenshot
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> URL
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Match Rate
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Status
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Corporation
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Account
                            </label>
                        </div>
                    </li>
                    <li class="close-dropdown">
                        Apply
                    </li>
                </ul>
            </div><!--#show-hide-->
            <?php /* <select id="corp_name" class="list-filter input-small select2" data-placeholder="Filter by Account">
                <option></option>
                <?php
                $filters = array(
                    'site_status'=>$this->params('site_status'),
                    'account_name'=>$this->params('account_name'),
                );
                $corps = Jien::model("Site")->select('corp_name, count(site_id) as count')->filter($filters)->groupBy('corp_name')->get()->rows();
                foreach($corps AS $corp){
                    $sel = '';
                    if($this->params('corp_name') == $corp['corp_name']){
                        $sel = 'selected';
                    }
                    echo "<option {$sel} value='{$corp['corp_name']}'>{$corp['corp_name']} ({$corp['count']})</option>";
                }
                ?>
            </select>
            <select id="account_name" class="list-filter input-small select2" data-placeholder="Filter by Corporation">
                <option></option>
                <?php
                $filters = array(
                    'site_status'=>$this->params('site_status'),
                );
                $accounts = Jien::model("Site")->select('account_name, count(site_id) as count')->filter($filters)->groupBy('account_name')->get()->rows();
                foreach($accounts AS $account){
                    $sel = '';
                    if($this->params('account_name') == $account['account_name']){
                        $sel = 'selected';
                    }
                    echo "<option {$sel} value='{$account['account_name']}'>{$account['account_name']} ({$account['count']})</option>";
                }
                ?>
            </select> */ ?>
        </div>
        <table class="table table-striped table-bordered datatable with-check wo-export">
            <thead>
                <tr class="advanced-search">
                    <th class="col-ignore"></th>
                    <th class="col-ignore"></th>
                    <th class="col-ignore"></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th class="col-ignore col-remove"></th>
                </tr>
                <tr>
                    <!--
                    <th class="col-checkbox"><input type="checkbox" id="title-checkbox" name="title-checkbox"></th>
                    -->
                    <th class="col-ignore" rel="site.orig_screen" style="width:130px !important;">Screenshot</th>
                    <th rel="site.url">URL</th>
                    <th rel="site.iframe">iFrame</th>
                    <th rel="site.match_rate"">Match*</th>
                    <th rel="site.site_status">Status</th>
                    <th rel="site.corp_name">Corporation</th>
                    <th rel="site.account_name">Account</th>
                    <th class="col-actions"></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($this->data AS $rows){ // $rows[0] - new, $rows[1] - old?>
                <tr>
                    <!--
                    <td><input type="checkbox"></td>
                    -->
                    <td style="text-align:center">
                        <?php if(count($rows) > 1){?>
                            <?php if($rows[0]['site_status']!='down' && $rows[0]['screen']!=''){ ?>
                                <a title="Current Screenshot" href="<?php echo $rows[1]['screen']; ?>" target="_blank"><img src="/admin/resize/?img_path=<?php echo $rows[1]['screen']; ?>&width=50" class="img-rounded"></a>
                                <a title="New Screenshot" href="<?php echo $rows[0]['screen']; ?>" target="_blank"><img src="/admin/resize/?img_path=<?php echo $rows[0]['screen']; ?>&width=50" class="img-rounded"></a>
                            <?php } else { ?>
                                <div class="no-screenshot">No<br>Screenshot<br>Available</div>
                            <?php } ?>
                        <?php } else { ?>
                            <?php if($rows[0]['site_status']!='down' && $rows[0]['screen']!=''){ ?>
                                <a href="<?php echo $rows[0]['screen']; ?>" target="_blank"><img src="/admin/resize/?img_path=<?php echo $rows[0]['screen']; ?>&width=50" class="img-rounded"></a>
                            <?php } else { ?>
                                <div class="no-screenshot">No<br>Screenshot<br>Available</div>
                            <?php } ?>
                        <?php } ?>
                    </td>
                    <td>
                        <a title="Primary URL" href="<?php echo $rows[0]['url']; ?>" target="_blank"><?php echo $rows[0]['url']; ?></a>
                        <?php if(!empty($rows[0]['alt_url'])){?>
                        <a title="Alternate URL" href="<?php echo $rows[0]['alt_url']; ?>" target="_blank"><?php echo $rows[0]['alt_url']; ?></a>
                        <?php } ?>
                    </td>
                    <td>
                        <?php if($rows[0]['iframe'] && empty($rows[0]['alt_url']) && !$rows[0]['iframe_ignore']){?>
                            <span class='label label-danger'>yes</span>
                        <?php }else if($rows[0]['iframe_ignore']){ ?>
                            <span class='label label-warning'>ignored</span>
                        <?php } ?>
                    </td>
                    <td>
                        <?php if($rows[0]['match_rate'] >= MATCH_RATE){ ?>
                            <span title="Primary URL Match Rate" class='label label-success'><?php echo $rows[0]['match_rate']; ?>%</span>
                        <?php }else if($rows[0]['match_rate'] > 0){ ?>
                            <span title="Primary URL Match Rate" class='label label-danger'><?php echo $rows[0]['match_rate']; ?>%</span>
                        <?php }else{ ?>
                            <span title="Primary URL Match Rate" class='label label-default'><?php echo $rows[0]['match_rate']; ?>%</span>
                        <?php } ?>
                            <br>
                        <?php if(!empty($rows[0]['alt_url'])){ ?>
                            <?php if($rows[0]['match_rate_alt'] >= MATCH_RATE){ ?>
                                <span title="Alternate URL Match Rate" class='label label-success'><?php echo $rows[0]['match_rate_alt']; ?>%</span>
                            <?php }else if($rows[0]['match_rate_alt'] > 0){ ?>
                                <span title="Alternate URL Match Rate" class='label label-danger'><?php echo $rows[0]['match_rate_alt']; ?>%</span>
                            <?php }else{ ?>
                                <span title="Alternate URL Match Rate" class='label label-default'><?php echo $rows[0]['match_rate_alt']; ?>%</span>
                            <?php } ?>
                        <?php } ?>
                    </td>
                    <td>
                        <?php
                        switch($rows[0]['site_status']){
                            case "active":
                                $site_status_class = 'success';
                                break;

                            case "inactive":
                                $site_status_class = 'info';
                                break;

                            case "down":
                                $site_status_class = 'danger';
                                break;

                            case "new":
                                $site_status_class = 'default';
                                break;

                            case "changed":
                                $site_status_class = 'warning';
                                break;

                        }
                        ?>
                        <span class="label label-<?php echo $site_status_class; ?>"><?php echo $rows[0]['site_status']; ?></span>
                    </td>
                    <!--<td><?php echo date("m/d/y H:i:s", strtotime($rows[0]['checked'])); ?></td>-->
                    <td><?php echo $rows[0]['corp_name']; ?></td>
                    <td><?php echo $rows[0]['account_name']; ?></td>
                    <td>

                        <a href="/admin/site/id/<?php echo $rows[0]['site_id']; ?>" class="btn btn-primary btn-action ttip" title="View"><span class="icon-eye-open"></span></a>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
        <div class="clearfix"></div>
        <hr>
        <div class="row">
            <small class="col-lg-12">*Needs to match <?php echo MATCH_RATE; ?>% or greater to pass.</small>
        </div>
        <div>&nbsp;</div>
    </div>
</div><!--.row-->
<script>
var listTable = $('.datatable').dataTable({
                    "aoColumnDefs": [
                        { "bSearchable": false, "bSortable": false, "aTargets": ['col-actions', 'col-checkbox', 'col-upload', 'col-ignore'] },
                        { "sClass": "col-actions", "aTargets": [-1] },
                        { "sClass": "col-checkbox", "aTargets": [0] }
                    ],
                });
$('.list-filter').change(function(e){
    var type = $(this).attr('id');
    var val = $(this).val();
    //console.log($(location));

    var vars = getUrlVars();
    var qs = '';
    
    var url = $(location).attr('pathname') + "?" + type + '=' + val;
    if(vars.account_name && type != 'account_name'){
        url = url + "&account_name=" + vars.account_name;
    }
    var s = url.replace(/page\/\d/, '');
    /*alert(s);
    console.log(url);*/
    window.location = s;
    
});
</script>