<div class="row" id="content">
    <form action="/admin/data" method="POST" class="trig_save form-horizontal">
        <input type="hidden" name="model" value="<?php echo $this->model; ?>">
        <input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">

        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab-account" data-toggle="tab">Account</a></li>
            <li><a href="#tab-profile" data-toggle="tab">Profile</a></li>
        </ul>

        <div class="tab-content">

            <div class="tab-pane active" id="tab-account">
                
                <div class="col-lg-5 col-lg-offset-1">
                    <input type="hidden" name="model" value="User"> <input type="hidden" name="id" value="5">

                    <div class="form-group">
                        <label for="username" class="col-lg-4 control-label">Username<span class="req">*</span></label>
                        <div class="col-lg-8">
                            <input class="form-control" name="username" value="admin" size="30" type="text" value="<?php echo $this->user['username']; ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email" class="col-lg-4 control-label">Email<span class="req">*</span></label>
                        <div class="col-lg-8">
                            <input class="form-control" name="email" size="30" type="text" value="<?php echo $this->user['email']; ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="password" class="col-lg-4 control-label">Password<span class="req">*</span></label>
                        <div class="col-lg-8">
                            <a href="#" class="btn btn-default trig_password" rel="password">Set Password</a>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="provider_id" class="col-lg-4 control-label">Provider ID<span class="req">*</span></label>
                        <div class="col-lg-8">
                            <input class="form-control" name="provider_id" value="<?php echo $this->user['provider_id']; ?>" size=
                            "30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="uid" class="col-lg-4 control-label">User ID<span class="req">*</span></label>
                        <div class="col-lg-8">
                            <input class="form-control" name="uid" size="30" type="text" value="<?php echo $this->user['uid']; ?>" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="role_id" class="col-lg-4 control-label">Role ID<span class="req">*</span></label>
                        <div class="col-lg-8">
                            <input class="form-control" name="role_id" size="30" type="text" value="<?php echo $this->user['role_id']; ?>">
                        </div>
                    </div>

                </div><!--.col-lg-4-->

                <div class="col-lg-3 col-lg-offset-1 well">
                    <div class="form-group">
                        <label class="col-lg-4 control-label">Created</label>
                        <div class="col-lg-8">
                            <p class="control-value">January 5, 2013 at 3:00pm</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-4 control-label">Last login</label>
                        <div class="col-lg-8">
                            <p class="control-value">January 5, 2013 at 3:00pm</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-4 control-label">IPs</label>
                        <div class="col-lg-8">
                            <p class="control-value">101.10.55.200<br>
                            101.10.55.200<br>
                            101.10.55.200<br>
                            101.10.55.200</p>
                        </div>
                    </div>
                </div><!--.col-lg-4-->

            </div><!--#tab-account-->

            <div class="tab-pane" id="tab-profile">

                <div class="col-lg-5">

                    <div class="form-group">
                        <label for="gender" class="col-lg-4 control-label">Gender</label>
                        <div class="col-lg-8">
                            <select class="form-control" name="gender">
                                <option value="male"<?php if ($this->user['gender'] == 'male') { echo ' selected'; } ?>>Male</option>
                                <option value="female"<?php if ($this->user['gender'] == 'female') { echo ' selected'; } ?>>Female</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="birthday" class="col-lg-4 control-label">Birthday</label>

                        <div class="col-lg-8">
                            <input class="small datepicker form-control" name="birthday" value="<?php echo $this->user['birthday']; ?>" size="30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="b_fname" class="col-lg-4 control-label">First name</label>

                        <div class="col-lg-8">
                            <input class="form-control" name="b_fname" value="<?php echo $this->user['b_fname']; ?>" size="30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="b_lname" class="col-lg-4 control-label">Last name</label>

                        <div class="col-lg-8">
                            <input class="form-control" name="b_lname" value="<?php echo $this->user['b_lname']; ?>" size="30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="b_addr1" class="col-lg-4 control-label">Address</label>

                        <div class="col-lg-8">
                            <input class="form-control" name="b_addr1" value="<?php echo $this->user['b_addr1']; ?>" size="30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="b_addr2" class="col-lg-4 control-label">Address line 2</label>

                        <div class="col-lg-8">
                            <input class="form-control" name="b_addr2" value="<?php echo $this->user['b_addr2']; ?>" size="30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="b_city" class="col-lg-4 control-label">City</label>

                        <div class="col-lg-8">
                            <input class="form-control" name="b_city" value="<?php echo $this->user['b_city']; ?>" size="30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="b_state" class="col-lg-4 control-label">State</label>

                        <div class="col-lg-8">
                            <input class="form-control" name="b_state" value="<?php echo $this->user['b_state']; ?>" size="30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="b_zip" class="col-lg-4 control-label">Zip</label>

                        <div class="col-lg-8">
                            <input class="form-control" name="b_zip" value="<?php echo $this->user['b_zip']; ?>" size="30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="b_country" class="col-lg-4 control-label">Country</label>

                        <div class="col-lg-8">
                            <input class="form-control" name="b_country" value="<?php echo $this->user['b_country']; ?>" size="30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="phone" class="col-lg-4 control-label">Phone</label>

                        <div class="col-lg-8">
                            <input class="form-control" name="phone" value="<?php echo $this->user['phone']; ?>" size="30" type="text">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="comment" class="col-lg-4 control-label">Notes</label>

                        <div class="col-lg-8">
                            <textarea name="comment" class="notes-area form-control"><?php echo $this->user['comment']; ?></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="token" class="col-lg-4 control-label">Token</label>

                        <div class="col-lg-8">
                            <input class="form-control" name="token" value="<?php echo $this->user['token']; ?>" size="30" type="text">
                        </div>
                    </div>
                </div><!--.col-lg-4.col-lg-offset-2-->

            </div>

        </div><!--.tab-content-->

    </form>
</div><!--#content.row-->

<script>
$(document).ready(function(){
	$('.trig_password').click(function(e){
		e.preventDefault();
		var target = $(this).attr('rel');
		var html = '<input type="password" class="medium" name="'+target+'" value="">';
		$(this).parent().html(html);
	});
});
</script>