<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon">
					<i class="icon-align-justify"></i>
				</span>
				<h5><?php echo ucfirst($this->model); ?> form</h5>
			</div>

			<div class="widget-content nopadding">
				<form action="/admin/data" method="POST" class="trig_save form-horizontal">
				<input type="hidden" name="model" value="<?php echo $this->model; ?>">
		  		<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">
				<?php
	          		$scheme = Jien::model($this->model)->scheme();
	          		foreach($scheme AS $field=>$values){
	          			$label = ucwords(str_replace('_', ' ', $field));
	          			$type = 'text';
	          			$class = 'large';
	          			$size = 30;

	          			// skip these
	          			if($values['PRIMARY'] == 1 || $field == 'created' || $field == 'updated' || $field == 'deleted' || $field == 'accessed' || $field == 'active'){
		          			continue;
		          		}

		          		$enum = '';
		          		if(strstr($values['DATA_TYPE'], 'enum')){
		          			$enum = $values['DATA_TYPE'];
		          			$enum = str_replace("enum(", '', $enum);
		          			$enum = str_replace(")", '', $enum);
		          			$enum = str_replace("'", '', $enum);
		          			$enum = explode(",", $enum);
		          		}

		          		switch($values['DATA_TYPE']){
		          			case 'varchar':
		          				if($values['LENGTH'] <= 32){
		          					$class = 'mini';
		          				}else if($values['LENGTH'] <= 64){
		          					$class = 'medium';
		          				}else if($values['LENGTH'] <= 128){
		          					$class = 'large';
		          				}else{
		          					$class = 'xlarge';
		          				}
		          			break;

		          			case 'tinyint':
		          				$class = 'mini';
		          			break;

		          			case 'int':
		          				$class = 'medium';
		          			break;

		          			case 'bigint':
		          				$class = 'large';
		          			break;

		          			case 'date':
		          				$class = 'small datepicker';
		          			break;

		          			case 'datetime':
		          				$class = 'small datepicker';
		          			break;

		          			case 'text':
		          				$type = 'textarea';
		          			break;
		          		}

	          			switch($field){
	          				case 'password':
	          					$type = 'password';
	          				break;

	          				case 'category_id':
	          					$type = 'category';
	          				break;
	          			}
	          			$value = '';
	          			$value = $this->data->row($field);
	          			$row = $this->data->row();

	          			$input = "";

	          			if(!empty($enum)) $type = 'enum';
                                        
                                        
                                        if( !empty($this->joins) ){
                                            $type = 'join';
                                        }                                        
                                        
	          			switch($type){
	          				default:
	          					$input = "<input class='{$class}' name='{$field}' value=\"{$value}\" size='{$size}' type='{$type}'>";
	          				break;

	          				case 'enum':
	          					$class = 'medium';
	          					$input = "<select class='{$class}' name='{$field}'>";
	          					$input .= "<option></option>";
	          					foreach($enum AS $choice){
	          						$sel = '';
	          						if($choice == $value){
	          							$sel = 'selected';
	          						}
	          						$input .= "<option {$sel} value='{$choice}'>{$choice}</option>";
	          					}
	          					$input .= "</select>";
	          				break;

	          				case "textarea":
	          					$input = "<textarea name='{$field}' rows='7' class='xxlarge'>{$value}</textarea>";
	          				break;

	          				case "wysiwyg":
	          					$input = "<textarea name='{$field}' class='xxlarge wysiwyg'>{$value}</textarea>";
	          				break;

	          				case "password":
	          					$input = "<a href='#' class='btn trig_password' rel='{$field}'>set password</a>";
	          				break;

	          				case "category":
	          					$class = 'medium';
	          					$input = "<select class='{$class}' name='{$field}'>";
	          					$input .= $this->CategoryDropdown($this->model, $row['category_id']);
	          					$input .= "</select>";
	          				break;
                                                case 'join':
                                                    if( array_key_exists($field, $this->joins) ){
                                                        $input = "<select name='$field'>";
                                                        $key = $this->joins[$field]['key'];
                                                        $val = $this->joins[$field]['value'];
                                                        
                                                        $input .= "<option></option>";
                                                        foreach($this->joins[$field]['array'] as $option){
                                                            if($option[$key] == $value){
                                                                $selected = "selected";
                                                            }else{
                                                                $selected = "";
                                                            }
                                                            
                                                            $input .= "<option value='{$option[$key]}' $selected>{$option[$val]}</option>";
                                                        }
                                                        $input .= "</select>";
                                                    }
                                                break;

	          			}
	          	?>
					<div class="control-group">
						<label class="control-label"><?php echo $label; ?></label>
						<div class="controls">
							<?php echo $input; ?>
						</div>
					</div>

	          	 <?php } ?>
                         <?php  if($this->model == 'QrCode'){ ?>
                            <div class="control-group">
                                    <label class="control-label">URL</label>
                                    <div class="controls">
                                        <?php echo Qr::url( $this->params('id') ); ?>
                                        <div class="qr">
                                            <script>$('.qr').qrcode( '<?php echo Qr::url( $this->params('id') ); ?>' );</script>
                                        </div>
                                    </div>
                            </div>    
                                
                                
                         <?     }?>
					<div class="form-actions">
						<input type="submit" class="btn btn-success primary" value="Save changes">&nbsp;<button type="reset" class="btn back">Cancel</button>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>

<script>
$(document).ready(function(){
	$('.trig_password').click(function(e){
		e.preventDefault();
		var target = $(this).attr('rel');
		var html = "<input type='password' class='medium' name='"+target+"' value=''>";
		$(this).parent().html(html);
	});
});
</script>