<div class="row" id="content">
    <div id="sidebar" class="col-lg-2">
        <h4>Categories</h4>
        <ul class="category-list">
        <?php
            $categories = Jien::model("Category")->where("type='Post'")->get()->rows();
            foreach($categories as $category){
                //print_r($category);
                
            }
            // echo '<div class="checkbox"><label><input type="checkbox"> '.$category['category'].'</label></div>';
            $category_id = $this->params('category_id');
            $categories = Jien::model("Category")->where("category.type = 'Post'")->orderBy("category.path ASC")->get()->rows();
            $html = '';
            foreach($categories AS $record){
                //print_r($record);
                $c = substr_count($record['path'], ',');
                $x = str_repeat('<span class="child-arrow">&ndash; </span>', $c);
                $sel = '';
                if ($c > 1)
                    $level = ' level-'.$c;
                else
                    $level = ' parent';
                if($category_id == $record['category_id']){
                    $sel = ' selected';
                }
                $html .= '<li class="'. $level . $sel .'">'. $x .'<a href="">'.$record['category'].'</a></li>';
            }
            echo $html;
        ?>
        </ul>
    </div><!--#sidebar-->

    <div class="col-lg-10">
        <div class="filters">
            <div class="show-hide btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Show <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> ID
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Title
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> User
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Category
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Created
                            </label>
                        </div>
                    </li>
                    <li class="close-dropdown">
                        Apply
                    </li>
                </ul>
            </div><!--#show-hide-->
            <select class="select2" rel="category_id" placeholder="Limit to category...">
                <?php echo $this->CategoryDropdown('Post', $this->params('category_id')); ?>
            </select>        
        </div><!--.filters-->
        <table class="table table-striped table-bordered datatable">
            <thead>
                <tr class="advanced-search">
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                <tr>
                    <th class="col-checkbox"><input type="checkbox"></td>
                    <th rel="p.post_id">ID</th>
                    <th rel="p.subject">Title</th>
                    <th rel="p.user_id">User</th>
                    <th rel="category.category_id">Category</th>
                    <th rel="p.created">Created</th>
                    <th class="col-actions" style="width:150px">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->data->rows() AS $key=>$value){ ?>
                <tr>
                    <td><input type="checkbox"></td>
                    <td><?php echo $value['post_id']; ?></td>
                    <td><?php echo $value['subject']; ?></td>
                    <td><?php echo $value['username']; ?></td>
                    <td><?php echo $value['category']; ?></td>
                    <td><?php echo date("m/d/y", strtotime($value['created'])); ?></td>
                    <td>
                        <a href="/admin/<?php echo strtolower($this->model); ?>/id/<?php echo $value[strtolower($this->model).'_id']; ?>" class="btn btn-primary btn-action ttip" title="View/Edit"><span class="icon-eye-open"></span></a>
                        <a href="/admin/delete/?model=<?php echo $this->model; ?>&id=<?php echo $value[strtolower($this->model).'_id'];s ?>" class="btn btn-action btn-danger ttip red trig_delete" rel="model=<?php echo $this->model; ?>|id=<?php echo $value[$this->primary]; ?>"><span class="icon-remove"></span></a>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div><!--.col-lg-10-->
    
</div><!--#content.row-->

<script>
    
var increment = 1; 
$('.show-hide .dropdown-menu li input').on("click", function(e){
    fnShowHide($(this).parent().parent().parent().index() + increment);
});

var listTable = $('.datatable').dataTable({
    "aoColumnDefs": [
        { "bSearchable": false, "bSortable": false, "aTargets": ['col-actions', 'col-checkbox', 'col-upload', 'col-ignore'] },
        { "sClass": "col-actions", "aTargets": [-1] }
    ],
    "sDom": 'T<"clear">lfrtip',
    "oTableTools": {
        "sSwfPath": "/themes/admin/swf/copy_csv_xls_pdf.swf",
        "aButtons": [
            {
                "sExtends": "xls",
                "sButtonText": '<span class="icon-share-alt"></span> Export'
            }
        ]
    }
});
</script>