<div class="row" id="content">
    <div class="col-lg-12">
        <table class="table table-bordered table-striped datatable with-check">
            <thead>
                <tr>
                    <th class="header"><input type="checkbox" id="title-checkbox" name="title-checkbox" /></th>
                    <th class="header" rel="role.role_id">#</th>
                    <th class="header" rel="role.role">Role</th>
                    <th class="header" rel="role.created">Created</th>
                    <th class="header">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->data->rows() AS $key=>$value){ ?>
                <tr>
                    <td><input type="checkbox" /></td>
                    <td><?php echo $value['role_id']; ?></td>
                    <td><?php echo $value['role']; ?></td>
                    <td><?php echo date("m/d/y", strtotime($value['created'])); ?></td>
                    <td>
                        <a href="/admin/<?php echo strtolower($this->model); ?>/id/<?php echo $value[$this->primary]; ?>" class="btn btn-primary btn-action"><span class="icon-pencil"></span></a>
                        <a href="/admin/delete/?model=<?php echo $this->model; ?>&id=<?php echo $value[$this->primary];; ?>" rel="model=<?php echo $this->model; ?>|id=<?php echo $value[$this->primary]; ?>" class="btn btn-danger btn-action trig_delete"><span class="icon-remove"></span></a>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div><!--.col-lg-12-->
</div><!--#content-->
<script>
var rolesTable = $('.datatable').dataTable({
                    "aoColumnDefs": [
                        { "bSearchable": false, "bSortable": false, "aTargets": ['col-actions', 'col-checkbox', 'col-upload', 'col-ignore'] } /* Disabled sorting */
                    ]
                });
</script>