<!--<ul class="treeview">
    <li><a href="/admin/account/id/1">TestAcct</a>
        <ul>
            <li><a href="/admin/corporation?1.0">TestCorp</a>
                <ul>
                    <li><a href="/admin/mid?1.0.0">barclay.test.com</a></li>
                </ul>
            </li>
            <li><a href="/admin/corporation?1.1">TestCorp</a>
                <ul>
                    <li><a href="/admin/mid?1.1.0">barclay.test.com</a></li>
                    <li><a href="/admin/mid?1.1.1">barclay.test.com</a></li>
                    <li><a href="/admin/mid?1.1.2">barclay.test.com</a></li>
                    <li><a href="/admin/mid?1.1.3">barclay.test.com</a></li>
                </ul>
            </li>
            <li><a href="/admin/corporation?1.2">TestCorp</a>
                <ul>
                    <li><a href="/admin/mid?1.2.0">barclay.test.com</a></li>
                    <li><a href="/admin/mid?1.2.1">barclay.test.com</a></li>
                    <li><a href="/admin/mid?1.2.2">barclay.test.com</a></li>
                    <li><a href="/admin/mid?1.1.3">barclay.test.com</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li><a href="/admin/account/id/1?2">TestAcct</a>
        <ul>
            <li><a href="/admin/corporation?2.0">TestCorp</a>
                <ul>
                    <li><a href="/admin/mid?2.0.0">barclay.test.com</a></li>
                </ul>
            </li>
            <li><a href="/admin/corporation?2.1">TestCorp</a>
                <ul>
                    <li><a href="/admin/mid?2.1.0">barclay.test.com</a></li>
                    <li><a href="/admin/mid?2.1.1">barclay.test.com</a></li>
                    <li><a href="/admin/mid?2.1.2">barclay.test.com</a></li>
                    <li><a href="/admin/mid?2.1.3">barclay.test.com</a></li>
                </ul>
            </li>
            <li><a href="/admin/corporation?2.2">TestCorp</a>
                <ul>
                    <li><a href="/admin/mid?2.2.0">barclay.test.com</a></li>
                    <li><a href="/admin/mid?2.2.1">barclay.test.com</a></li>
                    <li><a href="/admin/mid?2.2.2">barclay.test.com</a></li>
                    <li><a href="/admin/mid?2.2.3">barclay.test.com</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li><a href="/admin/account/id/1?3">TestAcct</a>
        <ul>
            <li><a href="/admin/corporation?3.0">TestCorp</a>
                <ul>
                    <li><a href="/admin/mid?3.0.0">barclay.test.com</a></li>
                </ul>
            </li>
            <li><a href="/admin/corporation?3.1">TestCorp</a>
                <ul>
                    <li><a href="/admin/mid?3.1.0">barclay.test.com</a></li>
                    <li><a href="/admin/mid?3.1.1">barclay.test.com</a></li>
                    <li><a href="/admin/mid?3.1.2">barclay.test.com</a></li>
                    <li><a href="/admin/mid?3.1.3">barclay.test.com</a></li>
                </ul>
            </li>
            <li><a href="/admin/corporation?3.2">TestCorp</a>
                <ul>
                    <li><a href="/admin/mid?3.2.0">barclay.test.com</a></li>
                    <li><a href="/admin/mid?3.2.1">barclay.test.com</a></li>
                    <li><a href="/admin/mid?3.2.2">barclay.test.com</a></li>
                    <li><a href="/admin/mid?3.2.3">barclay.test.com</a></li>
                </ul>
            </li>
        </ul>
    </li>
</ul>-->